######################################################################
# Automatically generated by qmake (2.01a) Tue Jun 6 23:33:10 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += queens.cpp send-more-money.cpp
